### ISSUE TITLE
fingerprint panic

### ISSUE THREAD

**Issue by LPX-E5BD8** [XiaoMi/soar#90]
```
./soar -query "create table a (a int);insert into a values(1)" -report-type=fingerprint
create table a (a int)
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/XiaoMi/soar/vendor/github.com/percona/go-mysql/query.Fingerprint(0xc420370340, 0x18, 0x11, 0xc420163720)
	/Users/lpx/code/gopath/src/github.com/XiaoMi/soar/vendor/github.com/percona/go-mysql/query/query.go:545 +0x4841
main.main()
	/Users/lpx/code/gopath/src/github.com/XiaoMi/soar/cmd/soar/soar.go:183 +0x95e
```

if change `insert into a values(1)` to `insert into a values (1)` that panic would disappear.

**Comment by martianzhang** [comment]
This issue relates with https://github.com/percona/go-mysql/pull/30
